---
- project:
    check:
      jobs:
        - deployment-tests

- job:
    name: deployment-tests
    parent: base
    description: Deploy and check
    extra-vars:
      deployment: dev
    run: playbooks/zuul-check.yml
    ansible-version: 5.9.0
    nodeset:
      nodes:
        - name: container
          label: cloud-fedora-37
