# Be aware that this image is used for all stages, so if a dependency is removed be sure that it is
# not required in anywhere

FROM registry.fedoraproject.org/fedora:41

ENV ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 \
    ANSIBLE_STDOUT_CALLBACK=debug

RUN dnf -y upgrade && \
    dnf -y install ansible python3-pip && \
    dnf clean all
