# Be aware that this image is used for all stages, so if a dependency is removed be sure that it is
# not required in anywhere

FROM fedora:34

ENV ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 \
    ANSIBLE_STDOUT_CALLBACK=debug

RUN dnf update -y && \
    dnf install -y ansible python3-pip && \
    dnf clean all
