FROM quay.io/centos/centos:stream9

RUN curl -L -o oc.tgz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz && \
    tar xvzf oc.tgz && \
    rm -f oc.tgz && \
    mv oc /usr/bin/ && \
    rm -f kubectl README.md

COPY import-images.sh /usr/bin/

CMD ["bash", "/usr/bin/import-images.sh"]
