# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# -------------------------------------------------------------------
# Variables needed by Ansible playbooks in playbooks/
# -------------------------------------------------------------------

# Openshift project/namespace name
project: fedora-source-git-prod

# Openshift cluster url
host: https://api.auto-prod.gi0n.p1.openshiftapps.com:6443

# oc login <the above host value>, oc whoami -t
# OR via Openshift web GUI: click on your login in top right corner, 'Copy Login Command', take the part after --token=
api_key: ""

# validate_certs: true

with_tokman: false

# with_fedmsg: true

# with_redis_commander: false

# with_flower: false

with_beat: false

with_dashboard: false

with_pushgateway: false

with_repository_cache: false

with_fluentd_sidecar: false

# image to use for service
# image: quay.io/packit/packit-service:{{ deployment }}

# image to use for worker
image_worker: quay.io/packit/hardly:{{ deployment }}

# image to use for fluentd sidecar
# image_fluentd: quay.io/packit/fluentd-splunk-hec:latest

# Path to secrets (in case you don't have it in the root of this project)
# path_to_secrets: ../secrets

# Used in dev/Zuul deployment to tag & push images to cluster.
# It's set to "/usr/bin/podman" if there's podman installed, or to 'docker' otherwise.
# If you still want to use docker even when podman is installed, set:
# container_engine: docker

celery_app: hardly.tasks

# Celery retry parameters
celery_retry_limit: 0
# celery_retry_backoff: 3

# Number of worker pods to be deployed to serve the queues
# workers_all_tasks: 1
# workers_short_running: 0
# workers_long_running: 0

# distgit_url: https://src.fedoraproject.org/
# distgit_namespace: rpms

sourcegit_namespace: "fedora/src"

pushgateway_address: ""
