---
validate_certs: true # noqa: var-naming[no-role-prefix]
service: "{{ lookup('env', 'SERVICE') | default('packit', True) }}" # noqa: var-naming[no-role-prefix]
deployment: "{{ lookup('env', 'DEPLOYMENT') }}" # noqa: var-naming[no-role-prefix]
tenant: packit # noqa: var-naming[no-role-prefix] # MP+ tenant
with_tokman: true # noqa: var-naming[no-role-prefix]
with_fedmsg: true # noqa: var-naming[no-role-prefix]
with_redis: false # noqa: var-naming[no-role-prefix]
with_redict: true # noqa: var-naming[no-role-prefix]
with_redis_commander: false # noqa: var-naming[no-role-prefix]
with_flower: false # noqa: var-naming[no-role-prefix]
with_dashboard: true # noqa: var-naming[no-role-prefix]
with_beat: true # noqa: var-naming[no-role-prefix]
with_pushgateway: true # noqa: var-naming[no-role-prefix]
with_repository_cache: true # noqa: var-naming[no-role-prefix]
repository_cache_storage: 4Gi # noqa: var-naming[no-role-prefix]
push_dev_images: false # noqa: var-naming[no-role-prefix]
with_fluentd_sidecar: false # noqa: var-naming[no-role-prefix]
postgres_version: 13 # noqa: var-naming[no-role-prefix]
image: quay.io/packit/packit-service:{{ deployment }} # noqa: var-naming[no-role-prefix]
image_worker: quay.io/packit/packit-worker:{{ deployment }} # noqa: var-naming[no-role-prefix]
image_fedmsg: quay.io/packit/packit-service-fedmsg:{{ deployment }} # noqa: var-naming[no-role-prefix]
image_dashboard: quay.io/packit/dashboard:{{ deployment }} # noqa: var-naming[no-role-prefix]
image_tokman: quay.io/packit/tokman:{{ deployment }} # noqa: var-naming[no-role-prefix]
image_fluentd: quay.io/packit/fluentd-splunk-hec:latest # noqa: var-naming[no-role-prefix]
# project_dir is set in tasks/project-dir.yml
path_to_secrets: "{{ project_dir }}/secrets/{{ service }}/{{ deployment }}" # noqa: var-naming[no-role-prefix]
# to be used in Image streams as importPolicy:scheduled value
auto_import_images: true # noqa: var-naming[no-role-prefix]
# used in dev/zuul deployment to tag & push images to cluster
# https://github.com/packit/deployment/issues/112#issuecomment-673343049
# container_engine: "{{ lookup('pipe', 'command -v podman 2> /dev/null || echo docker') }}"
container_engine: docker # noqa: var-naming[no-role-prefix]
celery_app: packit_service.worker.tasks # noqa: var-naming[no-role-prefix]
celery_retry_limit: 2 # noqa: var-naming[no-role-prefix]
celery_retry_backoff: 3 # noqa: var-naming[no-role-prefix]
workers_all_tasks: 1 # noqa: var-naming[no-role-prefix]
workers_short_running: 0 # noqa: var-naming[no-role-prefix]
workers_long_running: 0 # noqa: var-naming[no-role-prefix]
distgit_url: https://src.fedoraproject.org/ # noqa: var-naming[no-role-prefix]
distgit_namespace: rpms # noqa: var-naming[no-role-prefix]
sourcegit_namespace: "" # noqa: var-naming[no-role-prefix] # fedora-source-git only
pushgateway_address: http://pushgateway # noqa: var-naming[no-role-prefix]
# Check that the deployment repo is up-to-date
check_up_to_date: true # noqa: var-naming[no-role-prefix]
# Check that the current vars file is up-to-date with the template
check_vars_template_diff: true # noqa: var-naming[no-role-prefix]
deployment_repo_url: https://github.com/packit/deployment.git # noqa: var-naming[no-role-prefix]
# used by a few tasks below
k8s_apply: true # noqa: var-naming[no-role-prefix]
tokman: # noqa: var-naming[no-role-prefix]
  workers: 1
  resources:
    requests:
      memory: "88Mi"
      cpu: "5m"
    limits:
      memory: "128Mi"
      cpu: "50m"
appcode: PCKT-002 # noqa: var-naming[no-role-prefix]
registry: 172.30.1.1:5000 # noqa: var-naming[no-role-prefix]
registry_user: developer # noqa: var-naming[no-role-prefix]
