# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: redis
  labels:
    service: redis
spec:
  selector:
    service: redis
  template:
    metadata:
      labels:
        service: redis
        name: redis
    spec:
      containers:
        - name: redis
          image: quay.io/centos7/redis-5-centos7
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: "/var/lib/redis/data"
              name: redis-pv
          resources:
            limits:
              memory: "80Mi"
              cpu: "100m"
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc
  replicas: 1
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
