# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-commander
spec:
  selector:
    matchLabels:
      component: redis-commander
  template:
    metadata:
      labels:
        component: redis-commander
    spec:
      containers:
        - name: redis-commander
          image: rediscommander/redis-commander
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: HTTP_USER
              valueFrom:
                secretKeyRef:
                  key: redis-commander-user
                  name: redis-commander-secret
            - name: HTTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-commander-password
                  name: redis-commander-secret
          ports:
            - containerPort: 8081
          resources:
            # requests and limits have to be the same to have Guaranteed QoS
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "10m"
  replicas: 1
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    component: redis-commander
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: redis-commander
spec:
  to:
    kind: Service
    name: redis-commander
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
