# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "{{ path_to_secrets }}/id_rsa"
