# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Create empty files
  ansible.builtin.file:
    path: "{{ path_to_secrets }}/{{ item }}"
    state: touch
    mode: 0644
  loop:
    - fedora.keytab
    - sentry_key
    - flower-htpasswd
